# Generated by Django 6.0.3 on 2026-03-13 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.IntegerField(choices=[(1, '1 - Not Interested'), (2, '2 - Slightly Interested'), (3, '3 - Moderately Interested'), (4, '4 - Very Interested'), (5, '5 - Extremely Interested')])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.subject')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(related_name='students', through='hello.StudentSubject', to='hello.subject'),
        ),
    ]
# noop commit marker
