# Generated by Django 6.0.3 on 2026-03-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_category_subject_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('short_description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('place', models.CharField(max_length=255)),
                ('categories', models.ManyToManyField(blank=True, related_name='events', to='hello.category')),
            ],
        ),
    ]
