# Generated by Django 6.0.3 on 2026-03-14 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_category_subject_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubject',
            name='interest',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Not Interested'), (2, '2 - Slightly Interested'), (3, '3 - Moderately Interested'), (4, '4 - Very Interested'), (5, '5 - Extremely Interested')], null=True),
        ),
    ]
