# Generated by Django 6.0.3 on 2026-03-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPageUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('source', models.CharField(choices=[('litexpo', 'Litexpo'), ('meetup', 'Meetup'), ('kaveikti', 'Kaveikti'), ('other', 'Other')], max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
