# Generated by Django 6.0.3 on 2026-03-15 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_alter_studentsubject_interest'),
        ('hello', '0004_eventpageurl'),
    ]

    operations = [
    ]
